### PR TITLE
chore: update "dev:teamsAppId" to "teamsAppId"

### PR DESCRIPTION
**Pull request by kuojianlu**

### CODE REVIEW

**Review by JerryYangKai — APPROVED** [review]

**Review by swatDong — APPROVED** [review]

**Review by swatDong — APPROVED** [review]
Code change looks good.
Just confirm when to merge and which target branch? Since currently there's an active releasing...

**Comment by kuojianlu** [comment]
> Code change looks good. Just confirm when to merge and which target branch? Since currently there's an active releasing...

Will be merged after the active pre-release is published. Target brach is v3 (before v3 is merged back to dev).

**Review by SLdragon — APPROVED** [review]

**Comment by huimiu** [comment]
It seems that a sample was missed. This sample was merged to the v3 branch yesterday.

https://github.com/OfficeDev/TeamsFx-Samples/pull/715

**Comment by kuojianlu** [comment]
> It seems that a sample was missed. This sample was merged to the v3 branch yesterday.
> 
> #715

Thank you for the kind reminder. Updated.

**Pull request merged**
