### PR TITLE
docs(localdebug): add start local tunnel into cli preview steps

### PR DESCRIPTION
**Pull request by XiaofuHuang**
detail: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/17825928

### CODE REVIEW

**Comment by swatDong** [comment]
For other bot samples, will we add local cli part to readme?

**Comment by XiaofuHuang** [comment]
> For other bot samples, will we add local cli part to readme?

Not all of the templates and samples' readme files include information about the CLI preview process. In the prerelease branch, I'll only fix existing errors related to the CLI local preview steps. The unified readme format will be implemented in the dev branch.

**Review by MuyangAmigo — APPROVED** [review]

**Review by swatDong — APPROVED** [review]

**Comment by kuojianlu** [comment]
Target v3 branch.

**Comment by XiaofuHuang** [comment]
> Target v3 branch.

Thx! Updated.

**Review by yukun-dong — APPROVED** [review]

**Pull request merged**
