### PR TITLE
Updated readme with images to clarify debug

### PR DESCRIPTION
**Pull request by JoshuaPartlow**
Updated the readme for the Hello-world-teams-tab-and-outlook-addin sample with screenshots to better show the debug process.

### CODE REVIEW

**Comment by JoshuaPartlow** [comment]
Adding @erikadoyle for awareness and to add others as needed.

**Comment by erikadoyle** [comment]
@MSFT-yiz @1yefuwang1 @HuihuiWu-Microsoft could someone please help to review/merge? This fixes a MetaOS customer issue tracked by Dev Success team. Thank you!

**Review by HuihuiWu-Microsoft — APPROVED** [review]
LGTM, @1yefuwang1 can you help review since you're the owner of this sample in our team?

**Comment by erikadoyle** [comment]
Hi @1yefuwang1, would you mind helping review/merge? Thanks!

**Review by 1yefuwang1 — APPROVED** [review]

**Pull request merged**
